import { useState, useEffect } from 'react'
import { useParams, useNavigate, Link } from 'react-router-dom'
import { ArrowLeft, Download, History, CheckCircle, XCircle, Lightbulb, TrendingUp } from 'lucide-react'
import toast from 'react-hot-toast'
import ScoreCard from '../components/ScoreCard'
import SkillTag from '../components/SkillTag'
import SuggestionsList from '../components/SuggestionsList'
import { getResult } from '../services/api'

export default function ResultPage() {
  const { id } = useParams()
  const navigate = useNavigate()
  const [result, setResult] = useState(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    getResult(id)
      .then(setResult)
      .catch(() => {
        toast.error('Could not load results.')
        navigate('/')
      })
      .finally(() => setLoading(false))
  }, [id])

  function downloadReport() {
    const lines = [
      'SMART RESUME ANALYSIS REPORT',
      '='.repeat(40),
      '',
      `File        : ${result.filename}`,
      `Job Role    : ${result.jobRole}`,
      `Date        : ${new Date(result.createdAt).toLocaleDateString()}`,
      `Match Score : ${result.score}%`,
      '',
      `SKILLS FOUND (${result.skillsFound.length})`,
      '-'.repeat(30),
      ...result.skillsFound.map(s => `  • ${s}`),
      '',
      `MISSING SKILLS (${result.missingSkills.length})`,
      '-'.repeat(30),
      ...result.missingSkills.map(s => `  • ${s}`),
      '',
      'IMPROVEMENT SUGGESTIONS',
      '-'.repeat(30),
      ...result.suggestions.map((s, i) => `  ${i + 1}. ${s}`),
      '',
      '='.repeat(40),
      'Generated by Smart Resume Analyzer',
    ]

    const blob = new Blob([lines.join('\n')], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `resume-analysis-${result.id}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    toast.success('Report downloaded!')
  }

  if (loading) {
    return (
      <div className="loading-center">
        <div className="spinner-lg" />
      </div>
    )
  }

  if (!result) return null

  return (
    <div className="animate-in">
      {/* Actions bar */}
      <div className="result-actions">
        <button className="btn btn-outline" onClick={() => navigate('/')}>
          <ArrowLeft size={15} /> New Analysis
        </button>
        <button className="btn btn-outline" onClick={downloadReport}>
          <Download size={15} /> Download Report
        </button>
        <Link to="/history" className="btn btn-outline">
          <History size={15} /> View History
        </Link>
      </div>

      {/* Page title */}
      <div style={{ marginBottom: 24 }}>
        <h1 style={{ fontSize: 26, fontWeight: 800, color: 'var(--gray-900)', letterSpacing: '-.01em' }}>
          Analysis Results
        </h1>
        <p style={{ color: 'var(--text-muted)', marginTop: 4, fontSize: 14 }}>
          {result.filename} &nbsp;·&nbsp; {result.jobRole} &nbsp;·&nbsp;{' '}
          {new Date(result.createdAt).toLocaleDateString()}
        </p>
      </div>

      {/* Stats strip */}
      <div className="stats-row">
        <div className="stat-card">
          <div className="stat-icon" style={{ background: 'var(--success-50)', color: 'var(--success-500)' }}>
            <CheckCircle size={20} />
          </div>
          <div className="stat-info">
            <h3>{result.skillsFound.length}</h3>
            <p>Skills Found</p>
          </div>
        </div>
        <div className="stat-card">
          <div className="stat-icon" style={{ background: 'var(--danger-50)', color: 'var(--danger-500)' }}>
            <XCircle size={20} />
          </div>
          <div className="stat-info">
            <h3>{result.missingSkills.length}</h3>
            <p>Missing Skills</p>
          </div>
        </div>
        <div className="stat-card">
          <div className="stat-icon" style={{ background: 'var(--primary-50)', color: 'var(--primary-500)' }}>
            <TrendingUp size={20} />
          </div>
          <div className="stat-info">
            <h3>{result.score}%</h3>
            <p>Match Score</p>
          </div>
        </div>
      </div>

      {/* Score circle + skills */}
      <div className="results-grid">
        {/* Score */}
        <div className="card">
          <ScoreCard score={result.score} />
        </div>

        {/* Skills (found + missing stacked) */}
        <div className="card">
          <div className="card-header">
            <div className="card-icon green"><CheckCircle size={17} /></div>
            <h2 className="card-title">Skills Found ({result.skillsFound.length})</h2>
          </div>
          {result.skillsFound.length > 0
            ? <div className="skills-grid">
                {result.skillsFound.map(s => <SkillTag key={s} skill={s} type="found" />)}
              </div>
            : <p style={{ fontSize: 14, color: 'var(--text-muted)' }}>No matching skills detected.</p>
          }

          {result.missingSkills.length > 0 && (
            <>
              <div className="divider" />
              <div className="card-header" style={{ paddingBottom: 12, marginBottom: 12 }}>
                <div className="card-icon red"><XCircle size={17} /></div>
                <h2 className="card-title">Missing Skills ({result.missingSkills.length})</h2>
              </div>
              <div className="skills-grid">
                {result.missingSkills.map(s => <SkillTag key={s} skill={s} type="missing" />)}
              </div>
            </>
          )}
        </div>
      </div>

      {/* Suggestions */}
      <div className="card">
        <div className="card-header">
          <div className="card-icon yellow"><Lightbulb size={17} /></div>
          <h2 className="card-title">Improvement Suggestions</h2>
        </div>
        <SuggestionsList suggestions={result.suggestions} />
      </div>
    </div>
  )
}
